### ISSUE TITLE
vCard mit Bild

### ISSUE THREAD

**Issue by cod3monk** [fau-fablab/wp-fau-fablab-mods#1]
Wäre cool, wenn in der vCard auch gleich das Profilbild enthalten wäre.

**Comment by sedrubal** [comment]
Ist es eigentlich. Vermutlich geht irgendetwas nicht oder deine das VCard parst in deiner Kontakteapp nicht (das ist schon mal passiert). Ich hab aktuell keine Zeit, das zu debuggen :wink:

https://github.com/fau-fablab/wp-fau-fablab-mods/blob/647fdb7805392ba785e2e252cc48f91068d79e80/faufablab_liste_der_aktiven.php#L82

**Comment by cod3monk** [comment]
Eilt nicht, wäre nur schön zu haben. Im code sieht es nicht danach aus, als wenn das gehen sollte: https://github.com/fau-fablab/wp-fau-fablab-mods/blob/647fdb7805392ba785e2e252cc48f91068d79e80/faufablab_liste_der_aktiven.php#L76-L87

**Comment by cod3monk** [comment]
oh wait, du hast recht ;)

**Comment by sedrubal** [comment]
Das Bild wird base64 encodiert und dann hier inkludiert:

https://github.com/fau-fablab/wp-fau-fablab-mods/blob/647fdb7805392ba785e2e252cc48f91068d79e80/faufablab_liste_der_aktiven.php#L82

Das ist aber alles höchst fragil, weil ich kein guter PHP Programmierer bin :wink: 
Vermutlich zerfällt es in den Zeilen oben drüber...

**Comment by cod3monk** [comment]
Fixed in aa43cff6c2ddc630ceb29e523772f77d533aec44

**Comment by sedrubal** [comment]
Dankeschön ;)
